---
title: "Seamstresses - First Look"
author: "Grace Acton"
date: "2/15/2022"
output: 
  html_document: 
    theme: journal
---

## Loading Packages 

```{r load-packages-data}
library(tidyverse)

source("data_cleaning.R")
```

## Ad Year Distribution

```{r ad-years}
seamstresses %>% 
  ggplot(aes(x = year)) +
  geom_density()
```


## City Distribution
 
```{r city-bar-chart}
seamstresses %>% 
  filter(state == "MA", is.na(city) == FALSE) %>% 
  ggplot(mapping = aes(x = city)) +
  geom_bar() +
  coord_flip()
```
 ## Job Titles

```{r job-titles}
seamstresses_separated <- seamstresses %>% 
  separate_rows(job_title, sep = "; ") %>% 
  mutate(job_title = fct_collapse(job_title,
    Milliner = c("Milliner", "milliner"),
    Dressmaker = c("Dressmaker", "dressmaker"),
    Tailor = c("Tailor"),
    Tailoress = c("Tailoress", "tailoress"),
    Mantuamaker = c("Mantuamaker", "mantuamaker", "Mantua-Maker"),
    Apprentices = c("apprentices")
  ))

ggplot(seamstresses_separated, mapping = aes(x = job_title)) +
  geom_bar() +
  coord_flip()
```

```{r job-title-by-year}
seamstresses_separated %>% 
  filter(job_title == c("Dressmaker", "Mantuamaker", "Milliner", "Tailoress")) %>% 
  ggplot(mapping = aes(x = year, fill = job_title)) +
  geom_density(alpha = 0.5) +
  scale_fill_viridis_d()

```

## Age Distribution

```{r age-distribtuion}
ages %>% 
  ggplot(mapping = aes(x = age_ad)) +
  geom_density(aes(xmin = 0,
                   xmax = 60)) +
  labs(title = "Age at time of advertisement")
```

## Marriage Age

```{r marriage-age-distribution}
marriages %>% 
  ggplot(mapping = aes(x = age_marriage)) +
  geom_density(aes(xmin = 0,
                   xmax = 60)) +
  labs(title = "Age at time of marriage")
```

## Marriage Age and Ad Age (for married women)

```{r ages-marriage-ad}
marriages %>% 
  ggplot() +
  geom_density(mapping = aes(x = age_ad, xmin = 0, xmax = 60), color = "darkolivegreen") +
  geom_density(mapping = aes(x = age_marriage, xmin = 0, xmax = 60), color = "darkmagenta") 
  
```
```{r ad-vs-marriage-age}
marriages %>% 
  ggplot(mapping = aes(y = age_marriage, x = age_ad)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0)
```


