---
title: "Maps"
author: "Grace Acton"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r load-packages, echo=FALSE}

library(tidyverse) ## For plotting and data wrangling.

library(leaflet) ## For leaflet interactive maps

library(sf) ## For spatial data

library(RColorBrewer) ## For colour palettes

library(htmltools) ## For html

library(leafsync) ## For placing plots side by side

library(kableExtra) ## Table output

library(ggmap) ## for google geocoding

worcester_geo <- read_csv("data/worcester_geo_cleaned.csv")
ma_geo <- read_csv("data/ma_geo_cleaned.csv")
genealogy_geo <- read_csv("data/genealogy_cleaned.csv")
map_data <- read_csv("data/map_data_cleaned.csv")
job_title_popularity <- read_csv("data/job_titles_cleaned.csv")

```

## Base Map

```{r ggplot-map, echo=FALSE}

ggplot(data = map_data) +
  geom_sf(aes(geometry = geometry, fill = number)) +
  scale_fill_gradient(low = "lightskyblue", high = "midnightblue", na.value = "white") +
  labs(title = "Ads per Town",
       subtitle = "Massachusetts",
       color = "Number of Ads") +
  theme_void()
  
```
## Regionality of Job Titles

```{r job-title-map, echo=FALSE}
ggplot(job_title_popularity) +
  geom_sf(aes(geometry = geometry, fill = job_title)) +
  scale_fill_manual(values = c("Apprentices" = "lightpink", "Dressmaker" = "lightskyblue", "Mantuamaker" = "lightgoldenrod", "Milliner" = "thistle", "Tailor" = "lightslategray", "Tailoress" = "darkseagreen1"), na.value = "white") +
  labs(title = "Most Popular Job Title",
         subtitle = "By Town",
         color = "Job Title") +
  theme_void()
```

```{r worcester-map, echo=FALSE}

worcester_map <- leaflet(data = worcester_geo) %>% 
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>% 
  addCircleMarkers(
    radius = 6,
    fillColor = ~case_when(job_title == "Dressmaker" ~ "lightskyblue",
                      job_title == "Milliner" ~ "purple",
                      job_title == "Tailoress" ~ "yellow",
                      job_title == "Store Owner" ~ "lightgreen",
                      job_title == "Store owner" ~ "lightgreen",
                      job_title == "Milliner; Dressmaker" ~ "blueviolet",
                      job_title == "Milliner; dressmaker" ~ "blueviolet",
                      job_title == "Tailor" ~ "blue",
                      job_title == "Milliner; mantuamaker" ~ "magenta",
                      job_title == "Milliner; Mantua-Maker" ~ "magenta",
                      job_title == "Mantuamaker; Milliner" ~ "magenta",
                      job_title == "Tailoress; apprentices" ~ "orange"),
    color = "black",
    stroke = TRUE, 
    weight = 2,
    fillOpacity = 0.5,
    popup = ~popup) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE)
  )

worcester_map

```

## Locations of all Points in Seamstress Set

```{r ma-leaflet-map, echo = FALSE}

ma_map <- leaflet(data = ma_geo) %>% 
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>% 
  addCircleMarkers(
    radius = 6,
    fillColor = ~case_when(job_title == "Dressmaker" ~ "lightskyblue",
                      job_title == "Milliner" ~ "purple",
                      job_title == "Tailoress" ~ "yellow",
                      job_title == "Store Owner" ~ "lightgreen",
                      job_title == "Store owner" ~ "lightgreen",
                      job_title == "Milliner; Dressmaker" ~ "blueviolet",
                      job_title == "Milliner; dressmaker" ~ "blueviolet",
                      job_title == "Tailor" ~ "blue",
                      job_title == "Milliner; mantuamaker" ~ "magenta",
                      job_title == "Milliner; Mantua-Maker" ~ "magenta",
                      job_title == "Mantuamaker; Milliner" ~ "magenta",
                      job_title == "Tailoress; apprentices" ~ "orange"),
    color = "black",
    stroke = TRUE, 
    weight = 2,
    fillOpacity = 0.5,
    popup = ~ma_popup) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE)
  )

ma_map
```

```{r make-genealogy-map, echo=FALSE}

genealogy_map <- leaflet(data = genealogy_geo) %>% 
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>% 
  addCircleMarkers(
    radius = 6,
    fillColor = "#9cc1d1",
    color = "black",
    stroke = TRUE, 
    weight = 2,
    fillOpacity = 0.75,
    popup = ~genealogy_popup) %>% 
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE)
  )

genealogy_map
```

